// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1-PezSmCc3YIhgRDahR2wXD8b5vAVlds',
    appId: '1:41869776562:web:512d47b30547242901dbab',
    messagingSenderId: '41869776562',
    projectId: 'notesapp-46887',
    authDomain: 'notesapp-46887.firebaseapp.com',
    storageBucket: 'notesapp-46887.appspot.com',
    measurementId: 'G-HELSVK4LG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV24BmydOVSsd6n2jqFelC2dc0j4jKzeM',
    appId: '1:41869776562:android:5e98a9f64721b0a701dbab',
    messagingSenderId: '41869776562',
    projectId: 'notesapp-46887',
    storageBucket: 'notesapp-46887.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvxM3yB5jCZ4jr0y479FmWtBgyOXPJ13Q',
    appId: '1:41869776562:ios:4f1e75ca1464a0a501dbab',
    messagingSenderId: '41869776562',
    projectId: 'notesapp-46887',
    storageBucket: 'notesapp-46887.appspot.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvxM3yB5jCZ4jr0y479FmWtBgyOXPJ13Q',
    appId: '1:41869776562:ios:bb6329c94ab4171401dbab',
    messagingSenderId: '41869776562',
    projectId: 'notesapp-46887',
    storageBucket: 'notesapp-46887.appspot.com',
    iosBundleId: 'com.example.notesapp.RunnerTests',
  );
}
